// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umiryxoccksiicwglezx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtaXJ5eG9jY2tzaWljd2dsZXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTM2NjgsImV4cCI6MjA3MzI2OTY2OH0.b_s36PRjlhpVHdQgKFZlFZaeEvDDhe2GjVFKnRVFUiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});